### ISSUE TITLE
Shouldn't CMake be used as a build system?

### ISSUE THREAD

**Issue by KOLANICH** [microsoft/etl2pcapng#25]
To make it easier building without VisualStudio.

**Comment by maolson-msft** [comment]
CMake has many benefits for cross-platform building, but since etl2pcapng calls APIs that are not likely to ever be supported on an OS other than Windows, those benefits are not relevant to this project. Using CMake, then, would just add CMake as a dependency for building (and you'd still have to install Visual Studio, if I understand correctly). So you'll have to run the one-line command found in the Building section in the readme.

**Comment by KOLANICH** [comment]
>CMake has many benefits for cross-platform building, but since etl2pcapng calls APIs that are not likely to ever be supported on an OS other than Windows, those benefits are not relevant to this project. 

It is not about cross-platform building. It is about not using Visual Studio - proprietary app with telemetry that cannot even be downloaded without sending telemetry.

I don't want to have that on my PC. I prefer GCC+MinGW and Clang 13+MinGW.
